name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Update dummy_PATH
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo dummy_PATH=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2)/ >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v3
          
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install doxygen -y
        shell: bash

      - name: Install package
        run: pip3 install sphinx furo breathe sphinx-tabs
        shell: bash

      - name: Build sphinx docs
        run: |
          cd docs/sphinx/
          make html

      - name: Deploy the docs to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/sphinx/build/html
          target-folder: ${{ env.dummy_PATH }}
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: /version
